HR/HR/Controllers/public_charController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IHRBLL;
using IOC;
using Model;

namespace HR.Controllers
{
    public class public_charController : Controller
    {
        Ipublic_charBLL icb = IOCcotainer.Createpublic_charBLL();
        // GET: public_char
        public ActionResult Index()
        {
            List<public_charModel> list = icb.PCAll();
            return View(list);
        }

        // GET: public_char/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: public_char/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection,public_charModel pcm)
        {
            int result = icb.PCAdd(pcm);
            if (result>0)
            {
                return Content("<script>alert('新增成功哦');window.location.href='/public_char/Index'</script>");
            }
            else
            {
                return View();
            }
        }

        // GET: public_char/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: public_char/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        // POST: public_char/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            public_charModel pc = new public_charModel()
            {
                pbc_id = id
            };
            int result = icb.PCDelete(pc);
            if (result>0)
            {
                return Content("<script>alert('删除成功哦');window.location.href='/public_char/Index'</script>");
            }
            else
            {
                return Content("<script>alert('删除失败哦');window.location.href='/public_char/Index'</script>");
            }
        }
    }
}

HR/HR/Views/public_char/Create.cshtml

@model Model.public_charModel
<link href="~/css/table.css" rel="stylesheet" />
@using (Ajax.BeginForm("Create", "public_char", new AjaxOptions() { HttpMethod = "post" }))
{

    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <table width="100%">
                    <tr>
                        <td>
                            <font color="black">
                                您正在做的业务是：人力资源--客户化设置--人力资源档案管理设置--公共属性设置--公共属性添加
                            </font>
                        </td>
                    </tr>
                    <tr>
                        <td align="right">
                            <input type="submit" value="提交" class="BUTTON_STYLE1">
                            <input type="button" value="返回" class="BUTTON_STYLE1"
                                   onclick="history.back();">
                        </td>
                    </tr>
                </table>

                <table width="100%" border="1" cellpadding=0 cellspacing=1
                       bordercolorlight=#848284 bordercolordark=#eeeeee
                       class="TABLE_STYLE1">
                    <tr>
                        <td class="TD_STYLE1" width="20%">
                            属性种类
                        </td>
                        <td class="TD_STYLE2">
                            @Html.EditorFor(model => model.attribute_kind, new { htmlAttributes = new { @class = "TD_STYLE1" } })
                            @Html.ValidationMessageFor(model => model.attribute_kind, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <td class="TD_STYLE1">
                            属性名称
                        </td>
                        <td class="TD_STYLE2">
                            @Html.EditorFor(model => model.attribute_name, new { htmlAttributes = new { @class = "TD_STYLE1" } })
                            @Html.ValidationMessageFor(model => model.attribute_name, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
}

HR/HR/Views/public_char/Delete.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

HR/HR/Views/public_char/Index.cshtml
@model IEnumerable<Model.public_charModel>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/css/table.css" rel="stylesheet" />
</head>
<body>
    <table width="100%">
        <tr>
            <td>
                <font color="black">
                    您正在做的业务是：人力资源--客户化设置--人力资源档案管理设置--公共属性设置
                </font>
            </td>
        </tr>
        <tr>
            <td align="right">
                @Html.ActionLink("添加", "Create", new { }, new { @class = "BUTTON_STYLE1" })
            </td>
        </tr>
    </table>
    <table width="100%" border="1" cellpadding=0 cellspacing=1
           bordercolorlight=#848284 bordercolordark=#eeeeee
           class="TABLE_STYLE1">
        <tr>
            <td width="49%" class="TD_STYLE1">
                属性种类
            </td>
            <td width="44%" class="TD_STYLE1">
                属性名称
            </td>
            <td width="7%" class="TD_STYLE1" align="center">
                删除
            </td>
        </tr>
        <tr>
            <td class="TD_STYLE2">
                薪酬发放方式
            </td>
            <td class="TD_STYLE2"></td>
            <td class="TD_STYLE2" align="center">
                <a href="#">删除</a>
            </td>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td class="TD_STYLE2">
                    @Html.DisplayFor(modelItem => item.attribute_kind)
                </td>
                <td class="TD_STYLE2">
                    @Html.DisplayFor(modelItem => item.attribute_name)
                </td>
                <td class="TD_STYLE2" align="center">
                    @Html.ActionLink("删除", "Delete", new { id = item.pbc_id }, new { onclick = "return confirm('确认删除?')" })
                </td>
            </tr>
        }
        

    </table>
</body>
</html>