HR/HR/Controllers/majorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IHRBLL;
using IOC;
using Model;
using System.Data;

namespace HR.Controllers
{
    public class majorController : Controller
    {
        Iconfig_major_kindBLL icmkb = IOCcotainer.Createconfig_major_kindBLL();
        Iconfig_majorBLL icmb = IOCcotainer.Createconfig_majorBLL();
        // GET: major
        public ActionResult Index()
        {
            List<config_majorModel> list = icmb.Select();
            return View(list);
        }

        [HttpGet]
        // GET: major/Create
        public ActionResult Add()
        {
            DropList();
            return View();
        }

        private void DropList()
        {
            List<SelectListItem> list = new List<SelectListItem>();
            DataTable dt = icmkb.SelectType();
            foreach (DataRow dr in dt.Rows)
            {
                SelectListItem sl = new SelectListItem()
                {
                    Text = dr["major_kind_name"].ToString(),
                    Value = dr["major_kind_id"].ToString()
                };
                list.Add(sl);
            }
            ViewBag.dt = list;
        }
        
        [HttpPost]
        public ActionResult Add(config_majorModel cm)
        {
            if (ModelState.IsValid)//后台验证
            {
                string id = cm.major_kind_id;
                string name = icmkb.SelectById(id);
                config_majorModel cmm = new config_majorModel
                {
                    major_kind_id = cm.major_kind_id,
                    major_kind_name = name,
                    major_id = cm.major_id,
                    major_name = cm.major_name,
                    test_amount = 0
                };
                if (icmb.Add(cmm) > 0)
                {
                    return Content("<script>alert('新增成功!');window.location.href ='/major/Index';</script>");
                }
                else
                {
                    return Content("<script>alert('新增失败!');window.location.href ='/major/Add';</script>");
                }
            }
            else
            {
                return View(cm);
            }
        }

        // GET: major/Delete/5
        public ActionResult Delete(int id)
        {
            config_majorModel cfm = new config_majorModel()
            {
                mak_id=id
            };
            if (icmb.Del(cfm) > 0)
            {
                return Content("<script>alert('删除成功!');window.location.href ='/major/Index';</script>");
            }
            else
            {
                return Content("<script>alert('删除失败!');window.location.href ='/major/Index';</script>");
            }
        }
    }
}

HR/HR/Views/major/Add.cshtml
@model Model.config_majorModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
    <link href="~/css/table.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#ck").click(function () {
                $("#ckk").val($(this).val())
            })
        })
    </script>
</head>
<body>
    @using (Ajax.BeginForm("Add", "major", new AjaxOptions() { HttpMethod = "post" }))
    {
        <table width="100%">
            <tr>
                <td>
                    <font color="black">
                        您正在做的业务是：人力资源--客户化设置--人力资源档案管理设置--职位设置--职位添加
                    </font>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <input type="submit" value="提交" class="BUTTON_STYLE1">
                    <input type="button" value="返回" class="BUTTON_STYLE1"
                           onclick="history.back();">
                </td>
            </tr>
        </table>
            <table width="100%" border="1" cellpadding=0 cellspacing=1
                   bordercolorlight=#848284 bordercolordark=#eeeeee
                   class="TABLE_STYLE1">
                <tr>
                    <td class="TD_STYLE1" width="19%">
                        职位分类编号
                    </td>
                    <td class="TD_STYLE2" width="81%">
                        @Html.EditorFor(model => model.major_kind_id, new { htmlAttributes = new { @class = "form-control" ,@id="ckk",@readonly=true} })
                    </td>
                </tr>
                <tr>
                    <td class="TD_STYLE1" width="19%">
                        职位分类名称
                    </td>
                    <td class="TD_STYLE2" width="81%">
                        @Html.DropDownList("major_kind_name", @ViewBag.dt as IEnumerable<SelectListItem>, "", new { @class = "ck2", @id="ck"})
                    </td>
                </tr>
                <tr>
                    <td class="TD_STYLE1" width="19%">
                        职位编号
                    </td>
                    <td class="TD_STYLE2" width="81%">
                        @Html.EditorFor(model => model.major_id, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.major_id, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td class="TD_STYLE1" width="19%">
                        职位名称
                    </td>
                    <td class="TD_STYLE2" width="81%">
                        @Html.EditorFor(model => model.major_name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.major_name, "", new { @class = "text-danger" })
                    </td>
                </tr>
            </table>
    }    
</body>
</html>

HR/HR/Views/major/Index.cshtml
@model IEnumerable<Model.config_majorModel>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/css/table.css" rel="stylesheet" />
</head>
<body>
        <table width="100%">
            <tr>
                <td>
                    <font color="black">
                        您正在做的业务是：人力资源--客户化设置--人力资源档案管理设置--职位设置
                    </font>
                </td>
            </tr>
            <tr>
                <td align="right">
                    @Html.ActionLink("添 加", "Add", new { }, new { @class = "BUTTON_STYLE1",
                   style = "background-color:gainsboro;border-color:lightslategrey;"})
                </td>
            </tr>
        </table>
        <table width="100%" border="1" cellpadding=0 cellspacing=1
               bordercolorlight=#848284 bordercolordark=#eeeeee
               class="TABLE_STYLE1">
            <tr>
                <td width="22%" class="TD_STYLE1">
                    职位分类编号
                </td>
                <td width="23%" class="TD_STYLE1">
                    职位分类名称
                </td>
                <td width="26%" class="TD_STYLE1">
                    职位编号
                </td>
                <td width="24%" class="TD_STYLE1">
                    职位名称
                </td>
                <td width="5%" class="TD_STYLE1">
                    删除
                </td>
            </tr>
            @foreach (var item in Model) {
            <tr>
                <td class="TD_STYLE2">
                    @Html.DisplayFor(modelItem => item.major_kind_id)
                </td>
                <td class="TD_STYLE2">
                    @Html.DisplayFor(modelItem => item.major_kind_name)
                </td>
                <td class="TD_STYLE2">
                    @Html.DisplayFor(modelItem => item.major_id)
                </td>
                <td class="TD_STYLE2">
                    @Html.DisplayFor(modelItem => item.major_name)
                </td>
                <td class="TD_STYLE2">
                    @Html.ActionLink("删除", "Delete", new { id = item.mak_id }, new { onclick = "return confirm('确认删除?')" })
                </td>
            </tr>
        }
        </table>
        <p>
</body>
</html>