HR/HR/Controllers/file_third_kindController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IOC;
using IHRBLL;
using Model;
using Newtonsoft.Json;
using System.Data;

namespace HR.Controllers
{
    public class file_third_kindController : Controller
    {
        Iconfig_file_third_kindBLL ift = IOCcotainer.Createconfig_file_third_kindBLL();
        // GET: file_third_kind

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult RenStr()
        {
            List<config_file_third_kindModel> list = ift.FTKAll();
            return Content(JsonConvert.SerializeObject(list));
        }
        // GET: file_third_kind/Create
        public ActionResult Create()
        {
            Fi1();
            Fi2();
            return View();
        }

        // POST: file_third_kind/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection,config_file_third_kindModel ftk)
        {
            if (ModelState.IsValid)//后台验证
            {
                int result = ift.FTAdd(ftk);
            if (result > 0)
            {
                return Content("<script>alert('新增成功哦');window.location.href='/public_char/Index'</script>");
            }
            else
            {
                    
                    return Content("<script>alert('新增失败哦');window.location.href='/public_char/Create'</script>");
             }

            }
            else
            {
                return View();
            }
                
        }

        //查询I级机构名称绑定下拉框
        private void Fi1()
        {
            List<SelectListItem> list = new List<SelectListItem>();
            DataTable dt = ift.CX1();
            foreach (DataRow dr in dt.Rows)
            {
                SelectListItem sl = new SelectListItem()
                {
                     Text=dr["first_kind_name"].ToString(),
                      Value=dr["ffk_id"].ToString()
                };
                list.Add(sl);
            }
            ViewBag.dt = list;
        }
        //查询II级机构名称绑定下拉框
        private void Fi2()
        {
            List<SelectListItem> list = new List<SelectListItem>();
            DataTable dt = ift.CX2();
            foreach (DataRow dr in dt.Rows)
            {
                SelectListItem sl = new SelectListItem()
                {
                    Text = dr["second_kind_name"].ToString(),
                    Value = dr["fsk_id"].ToString()
                };
                list.Add(sl);
            }
            ViewBag.dt1 = list;
        }
        // GET: file_third_kind/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: file_third_kind/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: file_third_kind/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: file_third_kind/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HR/HR/Views/file_third_kind/Create.cshtml
@model Model.config_file_third_kindModel

@{
    ViewBag.Title = "Create";
}
<link href="~/css/table.css" rel="stylesheet" />
@using (Ajax.BeginForm("Create", "file_third_kind", new AjaxOptions() { HttpMethod = "post" }))
{
<table width="100%">
    <tr>
        <td>
            <font color="black">
                您正在做的业务是：人力资源--客户化设置--人力资源档案管理设置--III级机构设置--III级机构添加
            </font>
        </td>
    </tr>
    <tr>
        <td align="right">
            <input type="submit" value="提交" class="BUTTON_STYLE1">
            <input type="button" value="返回" class="BUTTON_STYLE1"
                   onclick="history.back();">
        </td>
    </tr>
</table>

<table width="100%" border="1" cellpadding=0 cellspacing=1
       bordercolorlight=#848284 bordercolordark=#eeeeee
       class="TABLE_STYLE1">
    <tr>
        <td width="19%" class="TD_STYLE1">
            I级机构名称
        </td>
        <td width="81%" class="TD_STYLE2">
               @Html.DropDownList("ffk_id", @ViewBag.dt as IEnumerable<SelectListItem>,"请选择I级机构名称")
                @Html.ValidationMessageFor(e => e.ftk_id)
            @*<select name="cftk.firstKindId" onchange="change1()" id="firstKindId" class="INPUT_STYLE1">
                <option value="0">请选择I机构名称</option>
            </select>*@
        </td>
    </tr>
    <tr>
        <td width="19%" class="TD_STYLE1">
            II级机构名称
        </td>
        <td width="81%" class="TD_STYLE2">
            @Html.DropDownList("fsk_id", @ViewBag.dt as IEnumerable<SelectListItem>, "请选择II级机构名称".ToString())
            @Html.ValidationMessageFor(e => e.ftk_id)
                   
            @*<select name="cftk.secondKindId" onchange="change2()" id="secondKindId" class="INPUT_STYLE1">
                <option value="0">
                    请选择II机构名称
                </option>

            </select>*@
        </td>
    </tr>
    <tr>
        <td width="19%" class="TD_STYLE1">
            III级机构编号
        </td>
        <td width="81%" class="TD_STYLE2">
                    @Html.EditorFor(model => model.third_kind_id, new { htmlAttributes = new { @class = "INPUT_STYLE1" } })
                    @Html.ValidationMessageFor(model => model.third_kind_id, "", new { @class = "text-danger" })
        </td>
    </tr>
    <tr>
        <td class="TD_STYLE1">
            III级机构名称
        </td>
        <td class="TD_STYLE2">
                    @Html.EditorFor(model => model.third_kind_name, new { htmlAttributes = new { @class = "INPUT_STYLE1" } })
                    @Html.ValidationMessageFor(model => model.third_kind_name, "", new { @class = "text-danger" })
        </td>
    </tr>
    <tr>
        <td class="TD_STYLE1">
            销售责任人编号（多个编号之间请用"半角逗号"加"一个空格"隔开，如", "）
        </td>
        <td class="TD_STYLE2">
                    @Html.TextAreaFor(model => model.third_kind_sale_id, new { htmlAttributes = new { @class = "TEXTAREA_STYLE1"} , @rows = "4", @cols = "120" })
                    @Html.ValidationMessageFor(model => model.third_kind_sale_id, "", new { @class = "text-danger" })
        </td>
    </tr>
    <tr>
        <td class="TD_STYLE1">
            是否为零售店（是/否）
        </td>
        <td class="TD_STYLE2">
            <select name="cftk.thirdKindIsRetail">
                <option selected="selected">是</option>
                <option>否</option>
            </select>

        </td>
    </tr>
</table>
}

HR/HR/Views/file_third_kind/Index.cshtml
@model IEnumerable<Model.config_file_third_kindModel>

@{
    ViewBag.Title = "Index";
}
<script src="~/Scripts/jquery-1.10.2.js"></script>
<link href="~/css/table.css" rel="stylesheet" />
<script src="~/Scripts/vue.js"></script>



<table width="100%">
    <tr>
        <td>
            <font color="black">
                您正在做的业务是：人力资源--客户化设置--人力资源档案管理设置--III级机构设置
            </font>
        </td>
    </tr>
    <tr>
        <td align="right">
            @Html.ActionLink("添加", "Create", new { },new { @class= "BUTTON_STYLE1" })
        </td>
    </tr>
</table>
<div id="div1">
    <table width="100%" border="1" cellpadding=0 cellspacing=1
           bordercolorlight=#848284 bordercolordark=#eeeeee
           class="TABLE_STYLE1">
        <tr>
            <td width="14%" class="TD_STYLE1">I级机构名称</td>
            <td width="14%" class="TD_STYLE1">II级机构名称 </td>
            <td width="14%" class="TD_STYLE1">II级机构编号 </td>
            <td width="14%" class="TD_STYLE1">III级机构名称</td>
            <td width="17%" class="TD_STYLE1">销售责任人编号 </td>
            <td width="17%" class="TD_STYLE1"> 是否为零售店 </td>
            <td width="5%" class="TD_STYLE1">变更</td>
            <td width="5%" class="TD_STYLE1">删除</td>
        </tr>
        <tr v-for="(item,index) in dt">
            <td>{{item.first_kind_name }}</td>
            <td>{{item.second_kind_name }}</td>
            <td>{{item.third_kind_id }}</td>
            <td>{{item.third_kind_name  }}</td>
            <td>{{item.third_kind_sale_id  }}</td>
            <td>{{item.third_kind_is_retail  }}</td>
            <td><a v-on:click="cz(item.ftk_id )" v-bind:href="['/file_third_kind/Update/'+item.Pid]">变更</a></td>
            <td><a v-on:click="cz(item.ftk_id )" v-bind:href="['/file_third_kind/Delete/'+item.Pid]">删除</a></td>
        </tr>
    </table>
</div>
<script type="text/javascript">
    var vm = new Vue({
        el: "#div1",
        data: {
            dt:null
        },
        methods: {
            load: function () {
                var t = this;
                $.ajax({
                    url: "/file_third_kind/RenStr",
                    type: "post",
                    data: "",
                    success: function (msg) {
                        var dd = eval("(" + msg + ")");
                        t.dt = dd;
                    }
                });
            }
        },
        created: function () {
            this.load();
        }
    });
</script>