HR/HR/Controllers/major_kindController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IOC;
using IHRBLL;
using Model;
using Newtonsoft.Json;

namespace HR.Controllers
{
    public class major_kindController : Controller
    {
        Iconfig_major_kindBLL icmkd = IOCcotainer.Createconfig_major_kindBLL();
        // GET: major_kind
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Sel()
        {
            List<config_major_kindModel> list = icmkd.Select();
            return Content(JsonConvert.SerializeObject(list));
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(config_major_kindModel cm)
        {
            if (ModelState.IsValid)//后台验证
            {
                int result = Convert.ToInt32(icmkd.MaxId());
                config_major_kindModel cmk = new config_major_kindModel()
                {
                    major_kind_id = (result + 1).ToString(),
                    major_kind_name = cm.major_kind_name
                };
                if (icmkd.Add(cmk) > 0)
                {
                    return Content("<script>alert('新增成功!');window.location.href ='/major_kind/Index';</script>");
                }
                else
                {
                    return Content("<script>alert('新增失败!');window.location.href ='/major_kind/Add';</script>");
                }
            }
            else
            {
                return View(cm);
            }
        }

        public ActionResult Delete(int id)
        {
            config_major_kindModel cmk = new config_major_kindModel()
            {
                mfk_id=id
            };
            if (icmkd.Del(cmk) > 0)
            {
                return Content("ok");
            }
            else
            {
                return Content("nook");
            }
        }
    }
}

HR/HR/Views/major_kind/Add.cshtml
@model Model.config_major_kindModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
    <link href="~/css/table.css" rel="stylesheet" />
    <script src="~/javascript/comm/comm.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    @using (Ajax.BeginForm("Add", "major_kind", new AjaxOptions() { HttpMethod = "post" }))
    {
        <table width="100%">
            <tr>
                <td>
                    <font color="black">
                        您正在做的业务是：人力资源--客户化设置--人力资源档案管理设置--职位分类设置--职位分类添加
                    </font>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <input type="submit" value="提交" class="BUTTON_STYLE1">
                    <input type="button" value="返回" class="BUTTON_STYLE1"
                           onclick="history.back();">
                </td>
            </tr>
        </table>
        <table width="100%" border="1" cellpadding=0 cellspacing=1
               bordercolorlight=#848284 bordercolordark=#eeeeee
               class="TABLE_STYLE1">
            <tr>
                <td class="TD_STYLE1" width="19%">
                    职位分类编号
                </td>
                <td class="TD_STYLE2" width="81%"></td>
            </tr>
            <tr>
                <td class="TD_STYLE1">
                    职位分类名称
                </td>
                <td class="TD_STYLE2">
                    @Html.EditorFor(model => model.major_kind_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.major_kind_name, "", new { @class = "text-danger" })
                </td>
            </tr>
        </table>
    }
</body>
</html>

HR/HR/Views/major_kind/Index.cshtml
@model IEnumerable<Model.config_major_kindModel>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/vue.js"></script>
    <link href="~/css/table.css" rel="stylesheet" />
    <script src="~/javascript/comm/comm.js"></script>
</head>
<body>
    <div id="Div1">
        <table width="100%">
            <tr>
                <td>
                    <font color="black">
                        您正在做的业务是：人力资源--客户化设置--人力资源档案管理设置--职位分类设置
                    </font>
                </td>
            </tr>
            <tr>
                <td align="right">
                    @Html.ActionLink("添 加", "Add", new { }, new { @class = "BUTTON_STYLE1",
                   style = "background-color:gainsboro;border-color:lightslategrey;" })
                </td>
            </tr>
        </table>
        <table width="100%" border="1" cellpadding=0 cellspacing=1
               bordercolorlight=#848284 bordercolordark=#eeeeee
               class="TABLE_STYLE1">
            <tr>
                <td width="46%" class="TD_STYLE1">
                    职位分类编号
                </td>
                <td width="47%" class="TD_STYLE1">
                    职位分类名称
                </td>
                <td width="5%" class="TD_STYLE1">
                    删除
                </td>
            </tr>
            @*<tr>
                <td class="TD_STYLE2">
                    01
                </td>
                <td class="TD_STYLE2">
                    销售
                </td>
                <td class="TD_STYLE2">
                    <a href="#">删除</a>
                </td>
            </tr>*@
            <tr v-for="(item,i) in dt">
                <td class="TD_STYLE2">{{item.major_kind_id}}</td>
                <td class="TD_STYLE2">{{item.major_kind_name}}</td>
                <td class="TD_STYLE2"><a href="#" v-on:click="Del(item.mfk_id)">删除</a></td>
            </tr>
        </table>
        <p>
</div>
    <script type="text/javascript">
        var vm = new Vue({
            el: "#Div1",
            data: {
                dt:null
            },
            methods: {
                load: function () {
                    var t = this;
                    $.ajax({
                        url: "/major_kind/Sel",
                        type: "post",
                        data: "",
                        success: function (msg) {
                            var dd = eval("(" + msg + ")");
                            t.dt = dd;
                        }
                    });
                },
                Del(obj) {
                    if (confirm('确定要删除吗')) {
                        var v = this;
                        var id = obj;
                        $.ajax({
                            url: "/major_kind/Delete",
                            type: "get",
                            data: "id="+id,
                            success: function (msg) {
                                if (msg=="ok") {
                                    alert("删除成功!!!")
                                    location.reload();
                                } else {
                                    alert("删除失败!!!")
                                    location.reload();
                                }
                            }
                        });
                    }
                }
            },
            created:function() {
                this.load();
            }
        });
    </script>
</body>
</html>